services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - 'data:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=moon'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    networks:
      - goals-net
  goals-node:
    container_name: goals-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_USERNAME=moon
      - MONGO_PASSWORD=secret
    depends_on:
      - mongodb
    networks:
      - goals-net
  goals-react:
    container_name: goals-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - goals-node
    networks:
      - goals-net

networks:
  goals-net:

volumes:
  data:
  logs:
